global_frame: map
update_frequency: 2.0
publish_frequency: 2.0
rolling_window: true
resolution: 0.05
width: 50
height: 50
track_unknown_space: true  # Should this be in obstacle layer?  # https://wiki.ros.org/navfn

plugins:
#    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
