global_frame: map
robot_base_frame: base_link
update_frequency: 2.0
publish_frequency: 2.0
rolling_window: true
resolution: 0.5
width: 500
height: 500

plugins:
#    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
