global_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 2.0
    publish_frequency: 2.0
    static_map: false
    rolling_window: true
    resolution: 0.5
    width: 500
    height: 500
