base_local_planner: base_local_planner/TrajectoryPlannerROS
base_global_planner: navfn/NavfnROS
recovery_behaviors: [
    {name: conservative_clear, type: clear_costmap_recovery/ClearCostmapRecovery},
    {name: aggressive_clear, type: clear_costmap_recovery/ClearCostmapRecovery}
]

conservative_clear:
    reset_distance: 3.00
aggressive_clear:
    reset_distance: 1.84

controller_patience: 2.0
planner_patience: 5.0
