# Current limits based on AZ3 standalone configuration.
acc_lim_x:  9
acc_lim_theta: 6.0
max_vel_x:  3.0
min_vel_x:  0.3
max_vel_theta: 2.0
min_vel_theta: -2.0
min_in_place_vel_theta: 0.1
escape_vel: -0.10
holonomic_robot: false

xy_goal_tolerance:  1
yaw_goal_tolerance: 0.5
latch_xy_goal_tolerance: true

sim_time: 1.7
sim_granularity: 0.025
vx_samples: 3
vtheta_samples: 20

# The documentation has different parameters, but is out of date
goal_distance_bias: 0.8
path_distance_bias: 0.6
occdist_scale: 0.01
heading_lookahead: 0.325
dwa: true

oscillation_reset_dist: 0.05
meter_scoring: true