version: "3.3"
services:
  spear:
    build:
      context: .
      dockerfile: Dockerfile
    image: spear
    container_name: spear-container
    tty: true
    stdin_open: true
    environment:
      DISPLAY: $DISPLAY
      ROS_IP: 192.168.1.13
      ROS_MASTER_URI: http://192.168.0.61:11311
      QT_X11_NO_MITSHM: 1
      DOCKER_HOST_REPO_LOCATION: .
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
      - .:/software
      - .docker-opt-ros-mount:/tmp/docker-opt-ros-mount
      - .docker-root-ros-include-mount:/tmp/docker-root-ros-include-mount
    privileged: true
    network_mode: host
