topics:
  - name: /feedback/camera_depth/image
    compress: true
    rate: 10.0
  - name: /tf
  - name: /tf_static
  - name: /joint_states

  - name: /arm_controller/state

  - name: /feedback/webcam1/image
    compress: true
    rate: 10.0
  - name: /feedback/webcam2/image
    compress: true
    rate: 10.0

  - name: /gps/fix
