set(_CATKIN_CURRENT_PACKAGE "MustafaNode")
set(MustafaNode_VERSION "0.0.0")
set(MustafaNode_MAINTAINER "vagrant <vagrant@todo.todo>")
set(MustafaNode_PACKAGE_FORMAT "2")
set(MustafaNode_BUILD_DEPENDS "rospy")
set(MustafaNode_BUILD_EXPORT_DEPENDS "rospy")
set(MustafaNode_BUILDTOOL_DEPENDS "catkin")
set(MustafaNode_BUILDTOOL_EXPORT_DEPENDS )
set(MustafaNode_EXEC_DEPENDS "rospy")
set(MustafaNode_RUN_DEPENDS "rospy")
set(MustafaNode_TEST_DEPENDS )
set(MustafaNode_DOC_DEPENDS )
set(MustafaNode_URL_WEBSITE "")
set(MustafaNode_URL_BUGTRACKER "")
set(MustafaNode_URL_REPOSITORY "")
set(MustafaNode_DEPRECATED "")