# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: case_arm
  joint_model_group_pose: rest
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_yaw
    - shoulder_pitch
    - elbow_pitch
    - wrist_pitch
    - wrist_roll
  sim_control_mode: 1  # 0: position, 1: velocity

controller_list:
  - name: arm_controller
    joints:
      - shoulder_yaw
      - shoulder_pitch
      - elbow_pitch
      - wrist_pitch
      - wrist_roll
    action_ns: 'follow_joint_trajectory'
    type: FollowJointTrajectory
