publish_tf: true

odom2: 'odometry/gps'
odom2_config: [
  true,  true,  true,
  false, false, false,
  false, false, false,
  false, false, false,
  false, false, false
]
odom2_diferential: false
odom2_queue_size: 10
