two_d_mode: true
map_frame: 'map'
odom_frame: 'odom'
base_link_frame: 'base_link'
frequency: 10

# [x, y, z
#  roll, pitch, yaw,
#  x vel, y vel, z vel,
#  roll vel, pitch vel, yaw vel,
#  x accel, y accel, z accel]

odom0: '/rover_diff_drive_controller/odom'
odom0_config: [
  true,  true,  true,
  false, false, false,
  false, false, false,
  false, false, false,
  false, false, false
]
odom0_differential: true
odom0_queue_size: 10

odom1: '/camera/odom'
odom1_config: [
  false, false, false,
  false, false, false,
  true,  true,  true,
  true,  true,  true,
  false, false, false
]
odom1_differential: false
odom1_queue_size: 10

imu0: '/imu/data'
imu0_config: [
  false, false, false,
  true,  true,  true,
  false, false, false,
  false, false, false,
  false,  false,  false
]
imu0_differential: false
imu0_queue_size: 10
