#:kivy 1.0.9

<Knob>:
    size: 100, 100
    	pos: self.pos
    	size: self.size
    min: 0
    max: 100
    step: 1
    value: 0  # Default position of knob.
    knobimg_source: "img/knob_metal.png"  # Knob texture
    show_label: True  # Show central label
    show_marker: True  # Show surrounding marker
    marker_img: "img/bline.png" # Marker texture image
    knob_size: 0.9  # Scales knob size to leave space for marker
    markeroff_color: 0, 0, 0, 0