#ifdef HARDWARE_INTERFACE_MAPPINGS_H_
#define HARDWARE_INTERFACE_MAPPINGS_H_

// Wheel numbers to use.
#define HW_IF_WHEEL_LEFT_1 0
#define HW_IF_WHEEL_LEFT_2 1

#define HW_IF_WHEEL_RIGHT_1 2
#define HW_IF_WHEEL_RIGHT_2 3


#endif // HARDWARE_INTERFACE_MAPPINGS_H_
