#!/usr/bin/env python
#
# This is just the plugin importer script that rqt requires. rqt will spin up
# the ros node for us as long as we use it's Main.main function.

import sys

from spear_station.rqt_arm_gui import ArmGuiPlugin
from rqt_gui.main import Main

plugin = 'rqt_arm_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
