#!/usr/bin/env python

import sys

from spear_station.rqt_arm_gui.test_module import MyPlugin
from rqt_gui.main import Main

plugin = 'rqt_arm_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
