<?xml version="1.0"?>
<!-- created with Phobos 0.8 -->

  <robot name="TARS_V2" xmlns:xacro="http://ros.org/wiki/xacro"> 
    <xacro:include filename="$(find spear_simulator)/models/rover/constants.xacro"/>
    <xacro:include filename="$(find spear_simulator)/models/rover/wheel.urdf.xacro"/>
    <xacro:include filename="$(find spear_simulator)/models/rover/arm.urdf.xacro"/>
    <xacro:include filename="$(find spear_simulator)/models/rover/zed_cam.urdf.xacro"/>
    <xacro:include filename="$(find spear_simulator)/models/rover/webcam.urdf.xacro"/>
    
    <link name="imu_link">
    </link>

    <link name="base_link">
      <!--<inertial>
        <origin xyz="0 0 0.19608" rpy="0 0 0"/>
        <mass value="30.0"/>
        <inertia ixx="0.79449" ixy="0" ixz="0" iyy="1.21074" iyz="0" izz="1.56825"/>
      </inertial>-->
      <visual name="visual_chassis">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://spear_simulator/models/rover/meshes/stl/TARS.V2.Chassis.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision name="collision_chassis">
        <origin xyz="0 0 0.19608" rpy="0 0 0"/>
        <geometry>
          <box size="0.63 0.48 0.29562"/>
        </geometry>
      </collision>
    </link>

    <link name="link_suspension_backleft">
      <inertial>
        <origin xyz="-0.12007 -0.01981 -0.04013" rpy="0 0 0"/>
        <mass value="0.75"/>
        <inertia ixx="0.00147" ixy="0" ixz="0" iyy="0.00598" iyz="0" izz="0.00469"/>
      </inertial>
      <visual name="visual_suspension_backleft">
        <origin xyz="0 0 0" rpy="0 0 -3.14159"/>
        <geometry>
          <mesh filename="package://spear_simulator/models/rover/meshes/stl/TARS.V2.Suspension.001.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision name="collision_suspension_backleft">
        <origin xyz="-0.12007 -0.01981 -0.04013" rpy="0 0 0"/>
        <geometry>
          <box size="0.27135 0.0381 0.14844"/>
        </geometry>
      </collision>
    </link>

    <link name="link_suspension_backright">
      <inertial>
        <origin xyz="-0.12007 0.02019 -0.04013" rpy="0 0 0"/>
        <mass value="0.75"/>
        <inertia ixx="0.00147" ixy="0" ixz="0" iyy="0.00598" iyz="0" izz="0.00469"/>
      </inertial>
      <visual name="visual_suspension_backright">
        <origin xyz="0 0 0" rpy="0 0 -3.14159"/>
        <geometry>
          <mesh filename="package://spear_simulator/models/rover/meshes/stl/TARS.V2.Suspension.001.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision name="collision_suspension_backright">
        <origin xyz="-0.12007 0.02019 -0.04013" rpy="0 0 0"/>
        <geometry>
          <box size="0.27135 0.0381 0.14844"/>
        </geometry>
      </collision>
    </link>

    <link name="link_suspension_frontleft">
      <inertial>
        <origin xyz="0.12007 -0.02019 -0.04013" rpy="0 0 0"/>
        <mass value="0.75"/>
        <inertia ixx="0.00147" ixy="0" ixz="0" iyy="0.00598" iyz="0" izz="0.00469"/>
      </inertial>
      <visual name="visual_suspension_frontleft">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://spear_simulator/models/rover/meshes/stl/TARS.V2.Suspension.001.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision name="collision_suspension_frontleft">
        <origin xyz="0.12007 -0.02019 -0.04013" rpy="0 0 0"/>
        <geometry>
          <box size="0.27135 0.0381 0.14844"/>
        </geometry>
      </collision>
    </link>

    <link name="link_suspension_frontright">
      <inertial>
        <origin xyz="0.12007 0.01981 -0.04013" rpy="0 0 0"/>
        <mass value="0.75"/>
        <inertia ixx="0.00147" ixy="0" ixz="0" iyy="0.00598" iyz="0" izz="0.00469"/>
      </inertial>
      <visual name="visual_suspension_frontright">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://spear_simulator/models/rover/meshes/stl/TARS.V2.Suspension.001.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision name="collision_suspension_frontright">
        <origin xyz="0.12007 0.01981 -0.04013" rpy="0 0 0"/>
        <geometry>
          <box size="0.27134 0.0381 0.14845"/>
        </geometry>
      </collision>
    </link>

    <xacro:wheel side="left" name="frontleft" offset="${WHEEL_SEP_LENGTH/2} ${WHEEL_SEP_WIDTH/2} 0"/>
    <xacro:wheel side="right" name="frontright" offset="${WHEEL_SEP_LENGTH/2} ${-WHEEL_SEP_WIDTH/2} 0"/>
    <xacro:wheel side="left" name="backleft" offset="${-WHEEL_SEP_LENGTH/2} ${WHEEL_SEP_WIDTH/2} 0"/>
    <xacro:wheel side="right" name="backright" offset="${-WHEEL_SEP_LENGTH/2} ${-WHEEL_SEP_WIDTH/2} 0"/>
    
    <xacro:zed_cam xyz="0.3 0 0.2" rpy="0 0 0"/>

    <xacro:webcam name="front" xyz="0.315 -0.11999 0.3439" rpy="0 0 0"/>
    <xacro:webcam name="back" xyz="-0.315 1e-05 0.3439" rpy="0 0 ${M_PI}"/>
    <xacro:webcam name="left" xyz="0 0.24 0.3439" rpy="0 0 ${M_PI/2}"/>
    <xacro:webcam name="right" xyz="0 -0.24 0.3439" rpy="0 0 ${-M_PI/2}"/>

    <joint name="imu_link" type="fixed">
      <origin xyz="0 0 0.2" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="imu_link"/>
    </joint>


    <joint name="link_suspension_backleft" type="fixed">
      <origin xyz="-0.15754 0.25888 0.07402" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="link_suspension_backleft"/>
    </joint>

    <joint name="link_suspension_backright" type="fixed">
      <origin xyz="-0.15754 -0.25922 0.07402" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="link_suspension_backright"/>
    </joint>

    <joint name="link_suspension_frontleft" type="fixed">
      <origin xyz="0.15754 0.25925 0.07402" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="link_suspension_frontleft"/>
    </joint>

    <joint name="link_suspension_frontright" type="fixed">
      <origin xyz="0.15755 -0.25885 0.07403" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="link_suspension_frontright"/>
    </joint>

    <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
        <legacyModeNS>true</legacyModeNS>
      </plugin>
    </gazebo>

    <gazebo>
      <plugin name="gps_controller" filename="libhector_gazebo_ros_gps.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>10.0</updateRate>
        <bodyName>base_link</bodyName>
        <topicName>/gps/fix</topicName>
        <velocityTopicName>/gps/fix_velocity</velocityTopicName>
        <referenceLatitude>51.45304</referenceLatitude>
        <referenceLongitude>-112.71593</referenceLongitude>
        <frameId>base_link</frameId>
      </plugin>
    </gazebo>

    <gazebo reference="imu_link">
      <gravity>true</gravity>
      <sensor name="imu_sensor" type="imu">
        <always_on>true</always_on>
        <update_rate>100</update_rate>
        <visualize>true</visualize>
        <topic>imu/data</topic>
        <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
          <topicName>imu/data</topicName>
          <bodyName>base_link</bodyName>
          <updateRateHZ>100.0</updateRateHZ>
          <gaussianNoise>0.0</gaussianNoise>
          <xyzOffset>0 0 0</xyzOffset>
          <rpyOffset>0 0 0</rpyOffset>
          <frameName>imu_link</frameName>
        </plugin>
        <pose>0 0 0 0 0 0</pose> <!--180 _ _-->
      </sensor>
    </gazebo>
  </robot>
