name: Update Wiki

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Upload documentation to wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: "doc"
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}
